//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp.Data_Layer.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_Order { get; set; }
        public int id_Person { get; set; }
        public Nullable<int> id_Product { get; set; }
        public int id_OrderType { get; set; }
        public bool Active { get; set; }
    
        public virtual OrderType OrderType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Product Product { get; set; }
    }
}
